services:
  backend:
    build: ./backend/api
    container_name: springboot
    # ports:
    #   - "${SPRINGBOOT_PORT_LOCAL}:${SPRINGBOOT_PORT_DOCKER}"
    networks:
      - network
    depends_on:
      - db

  db:
    image: mysql:8.0
    container_name: mysql-container
    env_file:
      - .env
    environment:
      MYSQL_ROOT_PASSWORD: ${MYSQL_ROOT_PASSWORD}
      MYSQL_DATABASE: ${MYSQL_DATABASE}
      MYSQL_USER: ${MYSQL_USER}
      MYSQL_PASSWORD: ${MYSQL_PASSWORD}
    ports:
      - "${MYSQL_PORT_LOCAL}:${MYSQL_PORT_DOCKER}"
    volumes:
      - mysql-data:/var/lib/mysql
      - ./db/mysql-init:/docker-entrypoint-initdb.d
    networks:
      - network

  swagger-ui:
    image: swaggerapi/swagger-ui:v5.32.0
    container_name: swagger
    ports:
      - "${SWAGGER_PORT_LOCAL}:${SWAGGER_PORT_DOCKER}"
    volumes:
      - ./backend/swagger/openapi.json:/usr/share/nginx/html/openapi.json
    environment:
      SWAGGER_JSON_URL: /openapi.json
    networks:
      - network

  nginx:
    image: nginx:alpine
    container_name: nginx
    ports:
      - "${NGINX_PORT_LOCAL}:${NGINX_PORT_DOCKER}"
    volumes:
      - ./nginx/conf.d:/etc/nginx/conf.d
      - ./backend/swagger:/usr/share/nginx/html/swagger
      # - ./frontend/build:/usr/share/nginx/html/frontend # cuando tengas frontend
    networks:
      - network
    depends_on:
      - backend

volumes:
  mysql-data:

networks:
  network:
    driver: bridge