services:
  db:
    image: mysql:8.0
    container_name: mysql-container
    env_file:
      - .env
    environment:
      MYSQL_ROOT_PASSWORD: ${MYSQL_ROOT_PASSWORD}
      MYSQL_DATABASE: ${MYSQL_DATABASE}
      MYSQL_USER: ${MYSQL_USER}
      MYSQL_PASSWORD: ${MYSQL_PASSWORD}
    ports:
      - "${MYSQL_PORT_LOCAL}:${MYSQL_PORT_DOCKER}"
    volumes:
      - mysql-data:/var/lib/mysql
      - ./db/mysql-init:/docker-entrypoint-initdb.d

  swagger-ui:
    image: swaggerapi/swagger-ui:v5.32.0
    container_name: swagger-container
    ports:
      - "8123:8080"
    volumes:
      - ./backend/swagger/openapi.json:/usr/share/nginx/html/openapi.json
    environment:
      SWAGGER_JSON_URL: /openapi.json

volumes:
  mysql-data: