services:
  backend:
    build: ./backend/api
    container_name: keyly-springboot
    ports:
      - "${SPRINGBOOT_PORT_LOCAL}:${SPRINGBOOT_PORT_DOCKER}"
    networks:
      - network
    # depends_on:
    #   - db

  db:
    image: mysql:8.0
    container_name: keyly-mysql
    env_file:
      - .env
    environment:
      MYSQL_ROOT_PASSWORD: ${MYSQL_ROOT_PASSWORD}
      MYSQL_DATABASE: ${MYSQL_DATABASE}
      MYSQL_USER: ${MYSQL_USER}
      MYSQL_PASSWORD: ${MYSQL_PASSWORD}
      LANG: C.UTF-8
    ports:
      - "${MYSQL_PORT_LOCAL}:${MYSQL_PORT_DOCKER}"
    volumes:
      - mysql-data:/var/lib/mysql
      - ./db/mysql-init:/docker-entrypoint-initdb.d
    networks:
      - network
    command: 
      --character-set-server=utf8mb4

  nginx:
    image: nginx:alpine
    container_name: keyly-nginx
    ports:
      - "${NGINX_PORT_LOCAL}:${NGINX_PORT_DOCKER}"
    volumes:
      - ./nginx/conf.d:/etc/nginx/conf.d
      # - ./frontend/build:/usr/share/nginx/html/frontend # cuando tengas frontend
    networks:
      - network

volumes:
  mysql-data:

networks:
  network:
    driver: bridge